version: 0.2

phases:
  install:
    commands:
      - echo installing nginx
      - sudo apt-get update
      - sudo apt-get install nginx -y
      - sudo service nginx start
  
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo Configuring nginx
artifacts:
  files:
    - /var/www/html/index.html
    - appspec.yml
    